<a href="https://colab.research.google.com/github/bill-ion-ux/bug-free-octo-happiness/blob/main/tutorial_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install opendatasets #install opendatasets, download new token in kaggel
#open token in notepad

In [3]:
import opendatasets as od
od.download("https://www.kaggle.com/datasets/rcratos/diabetes-risk-prediction") #ucrl link of the dataset

Please provide your Kaggle credentials to download this dataset. Learn more: http://bit.ly/kaggle-creds
Your Kaggle username: nabilirfan03
Your Kaggle Key: ··········
Dataset URL: https://www.kaggle.com/datasets/rcratos/diabetes-risk-prediction


100%|██████████| 2.54k/2.54k [00:00<00:00, 1.35MB/s]

In [4]:
import pandas as pd
data = pd.read_csv("/content/diabetes-risk-prediction/diabetes_risk_prediction_dataset.csv") # copy path of csv

In [5]:
data.head() #display a few of row of dataset

Age Gender Polyuria Polydipsia sudden weight loss weakness Polyphagia  \
0   40   Male       No        Yes                 No      Yes         No   
1   58   Male       No         No                 No      Yes         No   
2   41   Male      Yes         No                 No      Yes        Yes   
3   45   Male       No         No                Yes      Yes        Yes   
4   60   Male      Yes        Yes                Yes      Yes        Yes   

  Genital thrush visual blurring Itching Irritability delayed healing  \
0             No              No     Yes           No             Yes   
1             No             Yes      No           No              No   
2             No              No     Yes           No             Yes   
3            Yes              No     Yes           No             Yes   
4             No             Yes     Yes          Yes             Yes   

  partial paresis muscle stiffness Alopecia Obesity     class  
0              No              Yes      Yes     Yes  Positive  
1             Yes               No      Yes      No  Positive  
2              No              Yes      Yes      No  Positive  
3              No               No       No      No  Positive  
4             Yes              Yes      Yes     Yes  Positive

from matplotlib import pyplot as plt
_df_0['Age'].plot(kind='hist', bins=20, title='Age')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_1.groupby('Polyuria').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_2.groupby('Polydipsia').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_3.groupby('sudden weight loss').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_4.groupby('Polyphagia').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_5['Age'].plot(kind='line', figsize=(8, 4), title='Age')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['Polydipsia'].value_counts()
    for x_label, grp in _df_6.groupby('Polyuria')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('Polyuria')
_ = plt.ylabel('Polydipsia')

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['sudden weight loss'].value_counts()
    for x_label, grp in _df_7.groupby('Polydipsia')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('Polydipsia')
_ = plt.ylabel('sudden weight loss')

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['Polyphagia'].value_counts()
    for x_label, grp in _df_8.groupby('sudden weight loss')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('sudden weight loss')
_ = plt.ylabel('Polyphagia')

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['Genital thrush'].value_counts()
    for x_label, grp in _df_9.groupby('Polyphagia')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('Polyphagia')
_ = plt.ylabel('Genital thrush')

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_10['Polyuria'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_10, x='Age', y='Polyuria', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_11['Polydipsia'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_11, x='Age', y='Polydipsia', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_12['sudden weight loss'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_12, x='Age', y='sudden weight loss', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_13['Polyphagia'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_13, x='Age', y='Polyphagia', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

In [14]:
data.head(10) # display the first 19 row in dataset

Age Gender Polyuria Polydipsia sudden weight loss weakness Polyphagia  \
0   40   Male       No        Yes                 No      Yes         No   
1   58   Male       No         No                 No      Yes         No   
2   41   Male      Yes         No                 No      Yes        Yes   
3   45   Male       No         No                Yes      Yes        Yes   
4   60   Male      Yes        Yes                Yes      Yes        Yes   
5   55   Male      Yes        Yes                 No      Yes        Yes   
6   57   Male      Yes        Yes                 No      Yes        Yes   
7   66   Male      Yes        Yes                Yes      Yes         No   
8   67   Male      Yes        Yes                 No      Yes        Yes   
9   70   Male       No        Yes                Yes      Yes        Yes   

  Genital thrush visual blurring Itching Irritability delayed healing  \
0             No              No     Yes           No             Yes   
1             No             Yes      No           No              No   
2             No              No     Yes           No             Yes   
3            Yes              No     Yes           No             Yes   
4             No             Yes     Yes          Yes             Yes   
5             No             Yes     Yes           No             Yes   
6            Yes              No      No           No             Yes   
7             No             Yes     Yes          Yes              No   
8            Yes              No     Yes          Yes              No   
9             No             Yes     Yes          Yes              No   

  partial paresis muscle stiffness Alopecia Obesity     class  
0              No              Yes      Yes     Yes  Positive  
1             Yes               No      Yes      No  Positive  
2              No              Yes      Yes      No  Positive  
3              No               No       No      No  Positive  
4             Yes              Yes      Yes     Yes  Positive  
5              No              Yes      Yes     Yes  Positive  
6             Yes               No       No      No  Positive  
7             Yes              Yes       No      No  Positive  
8             Yes              Yes       No     Yes  Positive  
9              No               No      Yes      No  Positive

In [8]:
import numpy as np

array = np.array([[1,2],[2,3]])
print(array)

[[1 2]
 [2 3]]


In [12]:
array_random = np.random.randint(1,100,(2,2))
print(array_random)

[[64 94]
 [29 35]]


In [13]:
array_ones = np.ones((2,2))
array_zeros = np.zeros((2,2))
print(array_ones)
print(array_zeros)

[[1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]]


In [26]:
random_array = np.random.randint(1,100,(6,3)) #random.randint(Min,Max(row , column))
print(f"random array = \n{random_array} ")
transpose_array = np.transpose(random_array)
print(f"transpose array =  \n{transpose_array}")

random array = 
[[57 58 69]
 [86 20 18]
 [86 89  7]
 [ 1 18 63]
 [46 78 43]
 [23 33 11]] 
transpose array =  
[[57 86 86  1 46 23]
 [58 20 89 18 78 33]
 [69 18  7 63 43 11]]


In [28]:
#Create two random numpy array of size n x p and p x m and then compute the dot product
n = 5
m = 4
p = 3
array_1 = np.random.randint(1,100,(n,p))
array_2 = np.random.randint(1,100,(p,m))
dot_product = np.dot(array_1,array_2) #compute the dot product
print(f"array 1 is \n{array_1}")
print(f"array 2 is \n{array_2}")
print(f"dot product is \n{dot_product}")


array 1 is 
[[46 94 56]
 [13 71 83]
 [49 36  8]
 [92  2 63]
 [49 39 37]]
array 2 is 
[[72 39 52  1]
 [49 32 83 59]
 [41  3 65 46]]
dot product is 
[[10214  4970 13834  8168]
 [ 7818  3028 11964  8020]
 [ 5620  3087  6056  2541]
 [ 9305  3841  9045  3108]
 [ 6956  3270  8190  4052]]
